export const DASHBOARD = '/'
export const LOGIN = '/login'
export const SIGNUP = '/signup'
export const PROFILE = '/u/:username'
export const SUBKINCHOO = '/r/:subkinchooid'
export const FULLPOST = '/p/:postid'
export const NOT_FOUND = '/not-found'